services:
  # Flask application service
  growatt-api:
    build: .
    container_name: growatt-api
    restart: unless-stopped
    environment:
      - SECRET_KEY=change_this_to_a_random_secret_string
      - DEBUG=False
    volumes:
      - ./app:/app/app
    networks:
      - growatt-network

  # Nginx reverse proxy
  nginx:
    image: nginx:1.21-alpine
    container_name: growatt-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Uncomment when SSL is set up
    volumes:
      - ./nginx/growatt-api.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro # Uncomment when SSL is set up
      - ./app/static:/app/static:ro
    depends_on:
      - growatt-api
    networks:
      - growatt-network

networks:
  growatt-network:
    driver: bridge
