services:
  # Flask application service
  growatt-app:
    build: .
    container_name: growatt-app
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-growatt}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-growattpassword}
      - POSTGRES_DB=${POSTGRES_DB:-growattdb}
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    networks:
      - growatt-network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: growatt-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-growatt}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-growattpassword}
      - POSTGRES_DB=${POSTGRES_DB:-growattdb}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - growatt-network
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-growatt} -d ${POSTGRES_DB:-growattdb}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Nginx reverse proxy
  nginx:
    image: nginx:1.23-alpine # Updated to newer version
    container_name: growatt-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/growatt-api.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./app/static:/app/static:ro
    depends_on:
      growatt-app:
        condition: service_healthy # Only start when API is healthy
    networks:
      - growatt-network
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  postgres-data: # Persistent volume for PostgreSQL data
    driver: local

networks:
  growatt-network:
    driver: bridge
    # Enhanced network configuration
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
