name: Growatt Devices Collection

on:
  schedule:
    # Run every 15 minutes from 6 AM to 7 PM (UTC+7)
    - cron: "*/15 6-19 * * *"
  workflow_dispatch: # Manual trigger option
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'collect'
        type: choice
        options:
          - collect
          - export-only
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

jobs:
  collect_devices:
    runs-on: ubuntu-latest
    env:
      # Database connection
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # Growatt API credentials
      GROWATT_USERNAME: ${{ secrets.GROWATT_USERNAME }}
      GROWATT_PASSWORD: ${{ secrets.GROWATT_PASSWORD }}
      # Optional: Timezone setting
      TZ: "Asia/Bangkok" # Set to Thai timezone

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .  # Install the package in development mode

      - name: Create output directories
        run: |
          # Create logs directory
          mkdir -p logs
          # Create directory for storing device data
          mkdir -p data/devices

      - name: Run devices collection script
        if: ${{ github.event.inputs.action == 'collect' || github.event.inputs.action == '' || github.event_name == 'schedule' }}
        run: |
          # Add the current directory to PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          # Create output filename with timestamp
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          OUTPUT_FILE="data/devices/devices_${TIMESTAMP}.json"
          
          # Run the devices collector script (collect command)
          echo "Running devices_data_collector.py to collect data and update database..."
          python scripts/collectors/collect_devices_data.py collect
          
          # Export the data to a JSON file
          echo "Exporting collected data to $OUTPUT_FILE"
          python scripts/collectors/collect_devices_data.py export --output "$OUTPUT_FILE"
          
          echo "Device collection completed"
        env:
          # Database connection
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

          # Growatt API credentials
          GROWATT_USERNAME: ${{ secrets.GROWATT_USERNAME }}
          GROWATT_PASSWORD: ${{ secrets.GROWATT_PASSWORD }}

          # Optional: Timezone setting
          TZ: "Asia/Bangkok" # Set to Thai timezone
          
      - name: Export devices only
        if: ${{ github.event.inputs.action == 'export-only' }}
        run: |
          # Add the current directory to PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          # Create output filename with timestamp
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          OUTPUT_FILE="data/devices/devices_${TIMESTAMP}.json"
          
          # Export the data to a JSON file
          echo "Exporting database data to $OUTPUT_FILE"
          python scripts/collectors/collect_devices_data.py export --output "$OUTPUT_FILE"
          
          echo "Device export completed"
        env:
          # Database connection
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Optional: Timezone setting
          TZ: "Asia/Bangkok" # Set to Thai timezone
          
      - name: Debug data files
        run: |
          echo "Checking collected data files:"
          ls -la data/devices/
          
      - name: Upload device data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: device-data
          path: data/devices/*.json
          if-no-files-found: warn
