name: Growatt Data Collection Cron Job

on:
  schedule:
    # Runs every hour at minute 0
    - cron: "0 * * * *"
  workflow_dispatch: # Manual trigger option

jobs:
  collect_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .  # Install the package in development mode

      - name: Run data collection script
        run: |
          # Add the current directory to PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python scripts/collectors/collect_all_data.py
        env:
          # Database connection
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

          # Growatt API credentials
          GROWATT_USERNAME: ${{ secrets.GROWATT_USERNAME }}
          GROWATT_PASSWORD: ${{ secrets.GROWATT_PASSWORD }}

          # Optional: Timezone setting
          TZ: "Asia/Bangkok" # Set to your local timezone
