name: Data Report Job

on:
  schedule:
    # Runs on Monday at 8:00 AM
    - cron: "0 8 * * 1"
    # Runs on Saturday at 8:00 AM
    - cron: "0 8 * * 6"
  workflow_dispatch: # Manual trigger option
    inputs:
      days:
        description: "Number of days to include in the report"
        required: false
        default: "7"
        type: string
      email:
        description: "Email address to send the report to"
        required: false
        default: "enwuft@gmail.com"
        type: string

jobs:
  generate_report:
    runs-on: ubuntu-latest
    
    # Add PostgreSQL service container
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: growatt_db
        ports:
          - 5432:5432
        # Health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Thai fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-thai-tlwg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .  # Install the package in development mode
          pip install pandas matplotlib seaborn  # Install additional required packages

      - name: Setup database and run migrations
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -m app.db_migration
        env:
          # Database connection - use local postgres service container
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/growatt_db
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: growatt_db

      - name: Run database report script
        run: |
          # Add the current directory to PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:$(pwd)

          # Ensure reports directory exists
          mkdir -p reports

          # Get input parameters or use defaults
          DAYS="${{ github.event.inputs.days || '30' }}"
          EMAIL="${{ github.event.inputs.email }}"

          # Set more verbose output for debugging
          set -x
          
          # Run the script without the unsupported --output parameter
          if [ -z "$EMAIL" ]; then
            python scripts/reports/database_report.py --days $DAYS
          else
            python scripts/reports/database_report.py --days $DAYS --email $EMAIL
          fi
          
          # Copy any generated PDF reports to our reports directory for artifacts
          find . -name "*.pdf" -type f -mmin -60 -exec cp {} reports/ \;
          
          # Turn off verbose output
          set +x
          
          # List found reports
          echo "Found the following reports:"
          ls -la reports/
        env:
          # Database connection - use local postgres service container
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/growatt_db
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: growatt_db

          # Email configuration - use simple values for testing
          EMAIL_NOTIFICATIONS_ENABLED: "True"
          EMAIL_FROM: "noreply@example.com"
          EMAIL_TO: "admin@example.com"
          SMTP_SERVER: "localhost"
          SMTP_PORT: "25"
          SMTP_USERNAME: ""
          SMTP_PASSWORD: ""
          SMTP_USE_TLS: "True"

          # Timezone setting
          TZ: "Asia/Bangkok"

      - name: Debug report files
        run: |
          echo "Checking for generated report files:"
          find . -name "*.pdf" -type f -ls
          
      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-reports
          path: reports/*.pdf
          if-no-files-found: warn
          retention-days: 14 # Keep reports for 14 days
          
      - name: Download artifact (if needed)
        uses: actions/download-artifact@v4
        with:
          name: database-reports
          path: downloaded-reports
        # This step is optional and only needed if you want to process the reports further in this workflow
