name: Trigger auto deployment for growatt-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/growatt-api-AutoDeployTrigger-01696b41-7b09-4838-944a-fe31bc133230.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GROWATTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GROWATTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GROWATTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.GROWATTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GROWATTAPI_REGISTRY_PASSWORD }}
          containerAppName: growatt-api
          resourceGroup: Personal
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


